In [1]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy

In [2]:
iris = datasets.load_iris()

In [3]:
iris.data.shape

(150, 4)

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
unicos, quantidade = np.unique(iris.target, return_counts = True)
unicos, quantidade

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [7]:
r = skfuzzy.cmeans(data = iris.data.T, c=3 , m=2, error=0.005 , maxiter=1000, init=None)
# T -> Transpose
# c -> Número de clusters
# m -> Membership (default 2)
# error (default 0.005)
# maxiter -> Máximo de iterações
# init (default None)
r
# Retorna 
# cntr - Centro de cada cluster
# u - Resultados
# u0 - Ponto de partida
# d - Distâncias euclidianas
# jm - Histórico da função
# p - Número de iterações realizadas
# fpc - Coeficiente de particionamento difuso

(array([[5.00396449, 3.41412   , 1.48276481, 0.25352357],
        [6.77425028, 3.05216053, 5.64583288, 2.05317992],
        [5.88830251, 2.76084231, 4.36303158, 1.39684095]]),
 array([[9.96623643e-01, 9.75835983e-01, 9.79815133e-01, 9.67405510e-01,
         9.94469960e-01, 9.34538692e-01, 9.79480459e-01, 9.99546961e-01,
         9.30338014e-01, 9.82710464e-01, 9.68026864e-01, 9.92130963e-01,
         9.70621370e-01, 9.22931960e-01, 8.89718110e-01, 8.41287335e-01,
         9.46903416e-01, 9.96652231e-01, 9.04085595e-01, 9.79179916e-01,
         9.68581870e-01, 9.84825356e-01, 9.58643038e-01, 9.79407533e-01,
         9.66891719e-01, 9.73546200e-01, 9.94839398e-01, 9.93345014e-01,
         9.93673446e-01, 9.79500574e-01, 9.78710489e-01, 9.74347775e-01,
         9.38495743e-01, 9.04133595e-01, 9.85053569e-01, 9.84987070e-01,
         9.64168267e-01, 9.90889017e-01, 9.39650239e-01, 9.98287935e-01,
         9.94727386e-01, 8.50653088e-01, 9.52589993e-01, 9.79272040e-01,
         9.45234856e-

In [8]:
previsoes_porcentagem = r[1] # u - Resultados
previsoes_porcentagem

array([[9.96623643e-01, 9.75835983e-01, 9.79815133e-01, 9.67405510e-01,
        9.94469960e-01, 9.34538692e-01, 9.79480459e-01, 9.99546961e-01,
        9.30338014e-01, 9.82710464e-01, 9.68026864e-01, 9.92130963e-01,
        9.70621370e-01, 9.22931960e-01, 8.89718110e-01, 8.41287335e-01,
        9.46903416e-01, 9.96652231e-01, 9.04085595e-01, 9.79179916e-01,
        9.68581870e-01, 9.84825356e-01, 9.58643038e-01, 9.79407533e-01,
        9.66891719e-01, 9.73546200e-01, 9.94839398e-01, 9.93345014e-01,
        9.93673446e-01, 9.79500574e-01, 9.78710489e-01, 9.74347775e-01,
        9.38495743e-01, 9.04133595e-01, 9.85053569e-01, 9.84987070e-01,
        9.64168267e-01, 9.90889017e-01, 9.39650239e-01, 9.98287935e-01,
        9.94727386e-01, 8.50653088e-01, 9.52589993e-01, 9.79272040e-01,
        9.45234856e-01, 9.72127099e-01, 9.76781782e-01, 9.74205564e-01,
        9.77209876e-01, 9.97071214e-01, 4.45733840e-02, 2.92054347e-02,
        3.12519334e-02, 4.92206033e-02, 2.41509779e-02, 5.734205

In [9]:
previsoes_porcentagem[0][0] 
#[Primeiro Cluster][Primeiro registro] - Probabilidade de fazer parte desse grupo

0.9966236431412244

In [10]:
previsoes_porcentagem[1][0]
#[Segunda Cluster][Primeiro registro] - Probabilidade de fazer parte desse grupo

0.0010719022544143936

In [11]:
previsoes_porcentagem[2][0]
#[Terceiro Cluster][Primeiro registro] - Probabilidade de fazer parte desse grupo

0.0023044546043609754

In [12]:
previsoes = previsoes_porcentagem.argmax(axis=0)
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2], dtype=int64)

In [14]:
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[50,  0,  0],
       [ 0,  3, 47],
       [ 0, 37, 13]], dtype=int64)